spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/youtubematch?createDatabaseIfNotExist=true&useSSl=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9767
